meals/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from meals import views

app_name = 'meals'
urlpatterns = [
    path('<slug:slug>/', views.details, name='meals_details'),
    path('', views.list, name='meal_list'),
    path('sms/', views.sample),
    path('list/', views.index),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls'), name='meals'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.
class Meals(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField(max_length=500)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preperation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/images/')
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meals, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'

    def __str__(self):
        return self.name

meals/views.py
import requests
from django.shortcuts import render
from django.http import HttpRequest
from bs4 import BeautifulSoup

# Create your views here.
from meals.models import Meals


def Index(request):
    sr = request.POST['ser']
    ulr = 'https://www.google.co.in/search?q={}&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiBvdDr3NPoAhUSg-YKHXOFBl4Q_AUoA3oECBMQBQ&biw=1316&bih=630'.format(
        sr)
    return HttpRequest(ulr)


def index(request):
    context = {}
    return render(request, 'Base.html')


def list(request):
    meal_list = Meals.objects.all()
    context = {
        'mlist': meal_list,
    }
    return render(request, 'Meals/list.html', context)


def sample(request):
    URL = 'https://www.allrecipes.com/article/our-best-burrito-recipes/'
    # URL = "http://www.values.com/inspirational-quotes"
    r = requests.get(URL)

    quotes = []
    # soup = BeautifulSoup(r.content, 'html5lib')
    soup = BeautifulSoup(r.content, 'html.parser')
    div = soup.find('div', attrs={'class': 'article-content-container two-col-content-container'})

    for row in div.findAll('p'):
        print(row.text)
        print(row.text)
        # quote = {}
        # quote['theme'] = row.strong.text
        # quote['url'] = row.a['href']
        # quote['img'] = row.img['src']
        # quote['lines'] = row.h6.text
        # quote['author'] = row.p.text
        # quotes.append(quote)
        # print(soup.prettify())
    # print(div.prettify())
    return "Ht"


def details(request, slug):
    meals_details = Meals.objects.get(slug=slug)
    context = {'meals_details': meals_details}
    # context = {}
    return render(request, 'Meals/details.html', context)

meals/templates/Meals/Base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
</head>
<body>
<div class="container">

{% block content %}
{% endblock content %}

</div>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script crossorigin="anonymous"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

meals/templates/Meals/details.html
{% extends 'Base.html' %}
{% block content %}

<!--<div class="card" style="width: 18rem;">-->
<!--    <img alt="Card image cap" class="card-img-top" src="{{meals_details.image.url}}">-->
<!--    <div class="card-body">-->
<!--        <h5 class="card-title">{{meals_details.name}}</h5>-->
<!--        <p class="card-text">{{meals_details.description}}</p>-->
<!--        <p class="card-text">{{meals_details.people}}</p>-->
<!--        <p class="card-text">{{meals_details.price}}</p>-->
<!--        <p class="card-text">{{meals_details.preperation_time}}</p>-->
<!--    </div>-->
<!--</div>-->

<div class="d-flex item">
    <div class="image" data-aos="fade" style="background-image: url({{meals_details.image.url}});"></div>
    <div class="text">
        <h3>{{meals_details.name}}</h3>
        <p> {{meals_details.description}}</p>
        <p class="price">${{meals_details.price}}</p>
    </div>
</div> <!-- .item -->

{% endblock content %}

meals/templates/Meals/list.html
{% extends 'Base.html'%}

{% block Specialties %}

{% for h in mlist %}
    <a href="{%  url 'meals:meals_details' h.slug %}">
        {{ h }}
    </a>
{% endfor %}
{% endblock Specialties %}